// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqbhnkcshqrzemozkcui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxYmhua2NzaHFyemVtb3prY3VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNTkwMzcsImV4cCI6MjA2MjYzNTAzN30.rc51bdWXQ8s12bzuqvWCG6kVcmjNx7-iv5AaR0q03F0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);